### testing api call

#### User
#### Get User
GET http://localhost:8000/api/v1/users
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFAcy5jb20iLCJpYXQiOjE3Nzg1OTYzOTAsImV4cCI6MTc3ODY4Mjc5MH0.CrI9jr-9QrwVVuKQaNbvlOZxQCSV9thTtxXCiArFms8

#### Post User
POST http://localhost:8000/api/v1/users
Content-Type: application/json

{
    "name": "Anil",
    "email": "a@s.com",
    "password": "123"
}

#### Login User
POST http://localhost:8000/api/v1/users/login
Content-Type: application/json

{
    "email": "a@s.com",
    "password": "123"
}

#### Transcations: all private routers

### Post new transaction
POST http://localhost:8000/api/v1/transactions
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFAcy5jb20iLCJpYXQiOjE3Nzg1OTYzOTAsImV4cCI6MTc3ODY4Mjc5MH0.CrI9jr-9QrwVVuKQaNbvlOZxQCSV9thTtxXCiArFms8

{
    "type": "income",
  "title": "Salary",
  "amount": "55",
  "tDate": "23-04-2026"
}