### testing api call

#### User
#### Get User
GET http://localhost:8000/api/v1/users
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFAcy5jb20iLCJpYXQiOjE3NzkwMDMwMzMsImV4cCI6MTc3OTA4OTQzM30.fSza89TuU5LUlPvIViGRPpUw1ST248AFILf1R771IhU

#### Post User
POST http://localhost:8000/api/v1/users
Content-Type: application/json

{
    "name": "Anil",
    "email": "a@s.com",
    "password": "123"
}

#### Login User
POST http://localhost:8000/api/v1/users/login
Content-Type: application/json

{
    "email": "a@s.com",
    "password": "123"
}

#### Transcations: all private routers

### Post new transaction
POST http://localhost:8000/api/v1/transactions
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFAcy5jb20iLCJpYXQiOjE3NzkyNjY4ODMsImV4cCI6MTc3OTM1MzI4M30.o7Hm4mM_Oay8XJo_lahOPVRpK_DQ6PWd3wEwxSqO3ts

{
    "type": "income",
  "title": "Salary",
  "amount": "55",
  "tDate": "2026-04-23"
}

### Post new transaction
GET http://localhost:8000/api/v1/transactions
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFAcy5jb20iLCJpYXQiOjE3NzkwMDMwMzMsImV4cCI6MTc3OTA4OTQzM30.fSza89TuU5LUlPvIViGRPpUw1ST248AFILf1R771IhU

### Update by id new transaction
PATCH  http://localhost:8000/api/v1/transactions/6a09a248d21f155d427e44a0
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFAcy5jb20iLCJpYXQiOjE3NzkyNjY4ODMsImV4cCI6MTc3OTM1MzI4M30.o7Hm4mM_Oay8XJo_lahOPVRpK_DQ6PWd3wEwxSqO3ts

{
       
"type": "expenses",
"title": "Check",
"amount": "222222",
"tDate": "2026-05-06"

}

### Delete transaction
DELETE http://localhost:8000/api/v1/transactions
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFAcy5jb20iLCJpYXQiOjE3NzkwMDMwMzMsImV4cCI6MTc3OTA4OTQzM30.fSza89TuU5LUlPvIViGRPpUw1ST248AFILf1R771IhU

["6a06bd2b8aa25bd718e0086d","6a06c4eb8aa25bd718e00871"]